routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function() {

    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    
    Route::prefix('/settings')->name('settings.')->group(function() {
        Route::get('/', 'SettingsController@index');
        // Route::post('/', 'StateController@store')->name('store');
        // Route::post('/', 'StateController@store')->name('store');
        Route::post('/', 'SettingsController@settings')->name('settings');
        Route::prefix('/settings')->name('states.')->group(function() {
            Route::get('/{id}/destroy', 'StateController@destroy')->name('destroy');
        });
        Route::prefix('/customize')->name('customize.')->group(function() {
            Route::get('/', 'CustomizeController@index');
            //Falta armar los destroy de clients, products, y sales, pero tiene que validar si estan en uso a donde mover esos datos. o avisar que se van a borrar
            Route::prefix('/clients')->name('clients.')->group(function() {
                Route::get('/', 'CustomClientController@index');
                Route::post('/', 'CustomClientController@store')->name('store');
                Route::get('/{id}/destroy', 'CustomClientController@destroy')->name('destroy');
            });
            Route::prefix('/products')->name('products.')->group(function() {
                Route::get('/', 'CustomProductController@index');
                Route::post('/', 'CustomProductController@store')->name('store');
                Route::get('/{id}/destroy', 'CustomProductController@destroy')->name('destroy');
            });
            Route::prefix('/sales')->name('sales.')->group(function() {
                Route::get('/', 'CustomSaleController@index');
                Route::post('/', 'CustomSaleController@store')->name('store');
                Route::get('/{id}/destroy', 'CustomSaleController@destroy')->name('destroy');
            });
        });
    });

    Route::prefix('/sales')->name('sales.')->group(function() {
        Route::get('/destroy', 'SaleController@destroy')->name('destroy');
        Route::get('/', 'SaleController@index');
        Route::get('/new', 'SaleController@create')->name('create');
        Route::get('/{id}', 'SaleController@show')->name('show');
        Route::get('/{id}/edit', 'SaleController@edit')->name('edit');
        Route::post('/{id}/edit', 'SaleController@update')->name('update');
        Route::post('/new', 'SaleController@store')->name('store');
        Route::get('/{id}/edit/destroy', 'ProductSaleController@destroy')->name('product_destroy');
    });

    Route::prefix('/products')->name('products.')->group(function() {
        Route::get('/', 'ProductController@index');
        Route::get('/destroy', 'ProductController@destroy')->name('destroy');
        Route::get('/new', 'ProductController@create')->name('create');
        Route::get('/{id}/edit', 'ProductController@edit')->name('edit');
        Route::get('/{id}', 'ProductController@show')->name('show');
        Route::post('/new', 'ProductController@store')->name('store');
        Route::post('/{id}', 'ProductController@update')->name('update');
        Route::get('/{id}/edit/destroy', 'ProductProviderController@destroy')->name('provider_destroy');
        Route::post('/{id}/edit/add-provider', 'ProductProviderController@store')->name('add-provider');
    });

    Route::prefix('/clients')->name('clients.')->group(function() {
        Route::get('/destroy', 'ClientController@destroy')->name('destroy');
        Route::get('/', 'ClientController@index');
        Route::get('/new', 'ClientController@create')->name('create');
        Route::get('/{id}', 'ClientController@show')->name('show');
        Route::post('/new', 'ClientController@store')->name('store');
        Route::post('/{id}', 'ClientController@update')->name('update');
    });

    Route::prefix('/orders')->name('orders.')->group(function() {
        Route::get('/', 'SaleController@orders')->name('show_orders');
        Route::post('/', 'SaleController@orderUpdate')->name('orderUpdate');
    });

    Route::prefix('/providers')->name('providers.')->group(function() {
        Route::get('/', 'ProviderController@index')->name('index');
        Route::get('/{id}', 'ProviderController@show')->name('show');
        Route::get('/{id}/edit', 'ProviderController@edit')->name('edit');
        Route::post('/', 'ProviderController@store')->name('store');
        Route::post('/{id}', 'ProviderController@update')->name('update');
        Route::get('/destroy/{id}', 'ProviderController@destroy')->name('destroy');
        
    });
});

Route::get('logout', 'Auth\LoginController@logout');

Route::get('/artisan', 'ArtisanController@artisan')->name('artisan');

Route::get('/accept/{token}', 'InviteController@accept')->name('accept');
Route::post('/accept/{token}', 'SettingsController@registerInvite')->name('registerInvite');

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800">Panel</h1>
          <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Descargar Reporte</a>
        </div>

        <!-- Content Row -->
        <div class="row">

          <!-- Earnings (Monthly) Card Example -->
          <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
              <div class="card-body">
                <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Ganancia (mes actual)</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">${{number_format($revenueThisMonth)}}</div>
                  </div>
                  <div class="col-auto">
                    <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Earnings (Monthly) Card Example -->
          <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
              <div class="card-body">
                <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Ganancia (este año)</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">${{number_format($revenueThisYear)}}</div>
                  </div>
                  <div class="col-auto">
                    <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Earnings (Monthly) Card Example -->
          <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
              <div class="card-body">
                <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Ventas (mes actual)</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{number_format($salesAmmountThisYear)}}</div>
                  </div>
                  <div class="col-auto">
                    <i class="fas fa-sort-amount-up-alt fa-2x text-gray-300"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Pending Requests Card Example -->
          <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
              <div class="card-body">
                <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Total Ventas</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{$salesTotal}}</div>
                  </div>
                  <div class="col-auto">
                    <i class="fas fa-sort-amount-up-alt fa-2x text-gray-300"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Content Row -->

        <div class="row">

          <!-- Area Chart -->
          <div class="col-xl-8 col-lg-7">
            <div class="card shadow mb-4">
              <!-- Card Header - Dropdown -->
              <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Flujo de Ganancias (EN CONSTRUCCIÓN)</h6>
                <div class="dropdown no-arrow">
                  <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Dropdown Header:</div>
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
                </div>
              </div>
              <!-- Card Body -->
              <div class="card-body">
                <div class="chart-area">
                  <canvas id="myAreaChart"></canvas>
                </div>
              </div>
            </div>
          </div>

          <!-- Pie Chart -->
          <div class="col-xl-4 col-lg-5">
            <div class="card shadow mb-4">
              <!-- Card Header - Dropdown -->
              <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Ventas x Fuente (EN CONSTRUCCIÓN)</h6>
                <div class="dropdown no-arrow">
                  <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Dropdown Header:</div>
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
                </div>
              </div>
              <!-- Card Body -->
              <div class="card-body">
                <div class="chart-pie pt-4 pb-2">
                  <canvas id="myPieChart"></canvas>
                </div>
                <div class="mt-4 text-center small">
                  <span class="mr-2">
                    <i class="fas fa-circle text-primary"></i> Direct
                  </span>
                  <span class="mr-2">
                    <i class="fas fa-circle text-success"></i> Social
                  </span>
                  <span class="mr-2">
                    <i class="fas fa-circle text-info"></i> Referral
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Content Row -->
        {{-- <div class="row">

          <!-- Content Column -->
          <div class="col-lg-6 mb-4">

            <!-- Project Card Example -->
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Projects</h6>
              </div>
              <div class="card-body">
                <h4 class="small font-weight-bold">Server Migration <span class="float-right">20%</span></h4>
                <div class="progress mb-4">
                  <div class="progress-bar bg-danger" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <h4 class="small font-weight-bold">Sales Tracking <span class="float-right">40%</span></h4>
                <div class="progress mb-4">
                  <div class="progress-bar bg-warning" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <h4 class="small font-weight-bold">Customer Database <span class="float-right">60%</span></h4>
                <div class="progress mb-4">
                  <div class="progress-bar" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <h4 class="small font-weight-bold">Payout Details <span class="float-right">80%</span></h4>
                <div class="progress mb-4">
                  <div class="progress-bar bg-info" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <h4 class="small font-weight-bold">Account Setup <span class="float-right">Complete!</span></h4>
                <div class="progress">
                  <div class="progress-bar bg-success" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>

            <!-- Color System -->
            <div class="row">
              <div class="col-lg-6 mb-4">
                <div class="card bg-primary text-white shadow">
                  <div class="card-body">
                    Primary
                    <div class="text-white-50 small">#4e73df</div>
                  </div>
                </div>
              </div>
              <div class="col-lg-6 mb-4">
                <div class="card bg-success text-white shadow">
                  <div class="card-body">
                    Success
                    <div class="text-white-50 small">#1cc88a</div>
                  </div>
                </div>
              </div>
              <div class="col-lg-6 mb-4">
                <div class="card bg-info text-white shadow">
                  <div class="card-body">
                    Info
                    <div class="text-white-50 small">#36b9cc</div>
                  </div>
                </div>
              </div>
              <div class="col-lg-6 mb-4">
                <div class="card bg-warning text-white shadow">
                  <div class="card-body">
                    Warning
                    <div class="text-white-50 small">#f6c23e</div>
                  </div>
                </div>
              </div>
              <div class="col-lg-6 mb-4">
                <div class="card bg-danger text-white shadow">
                  <div class="card-body">
                    Danger
                    <div class="text-white-50 small">#e74a3b</div>
                  </div>
                </div>
              </div>
              <div class="col-lg-6 mb-4">
                <div class="card bg-secondary text-white shadow">
                  <div class="card-body">
                    Secondary
                    <div class="text-white-50 small">#858796</div>
                  </div>
                </div>
              </div>
            </div>

          </div>

          <div class="col-lg-6 mb-4">

            <!-- Illustrations -->
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Illustrations</h6>
              </div>
              <div class="card-body">
                <div class="text-center">
                  <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="{{url('storage/undraw_posting_photo.svg')}}" alt="">
                </div>
                <p>Add some quality, svg illustrations to your project courtesy of <a target="_blank" rel="nofollow" href="https://undraw.co/">unDraw</a>, a constantly updated collection of beautiful svg images that you can use completely free and without attribution!</p>
                <a target="_blank" rel="nofollow" href="https://undraw.co/">Browse Illustrations on unDraw &rarr;</a>
              </div>
            </div>

            <!-- Approach -->
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Development Approach</h6>
              </div>
              <div class="card-body">
                <p>SB Admin 2 makes extensive use of Bootstrap 4 utility classes in order to reduce CSS bloat and poor page performance. Custom CSS classes are used to create custom components and custom utility classes.</p>
                <p class="mb-0">Before working with this theme, you should become familiar with the Bootstrap framework, especially the utility classes.</p>
              </div>
            </div>

          </div>
        </div> --}}

      </div>
          <!-- Page level plugins -->
    <script src="{{ asset('/vendor/chart.js/Chart.min.js') }}"></script>
  
    <!-- Page level custom scripts -->
    <script src="{{ asset('/js/demo/chart-area-demo.js') }}"></script>
    <script src="{{ asset('/js/demo/chart-pie-demo.js') }}"></script>

    {{-- TOY TRATANDO DE QUE TRAIGA LA GANANCIA DE TODOS LOS MESES Y LO AGARRE EL CHART DE GANANCIA ANUAL. PERO LO TRAE NADA MAS DESDE ACA Y NO DESDE EL ARCHIVO --}}
    <script>
      var probando = {!! json_encode($probando) !!};
      console.log(probando)
    </script>

@endsection

resources/views/invite.blade.php
@extends('layouts.applogin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Register') }}</div>

                <div class="card-body">
                    <p>Te invitaron a sumarte a una empresa en Vanxa, completa el formulario para sumarte!</p>
                    <form method="POST" action="{{ route('registerInvite', $invite['token']) }}">
                        @csrf

                        <input type="hidden" name="company_id" value="{{$invite['company_id']}}">
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Nombre</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">E-Mail</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{$invite['email']}}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">Contraseña</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">Confirmar Contraseña</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/settings.blade.php
@extends('layouts.app')

@section('content')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Ajustes</h1>
</div>
    
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="state-tab" data-toggle="tab" href="#state" role="tab" aria-controls="state" aria-selected="true">Estados</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="adduser-tab" data-toggle="tab" href="#adduser" role="tab" aria-controls="adduser" aria-selected="false">Agregar Usuario</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="perfil-tab" data-toggle="tab" href="#perfil" role="tab" aria-controls="perfil" aria-selected="false">Perfil</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="company-tab" data-toggle="tab" href="#company" role="tab" aria-controls="company" aria-selected="false">Empresa</a>
    </li>
</ul>
<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="state" role="tabpanel" aria-labelledby="state-tab">
        <p class="mt-3">Editar los estados de la venta:</p>
        <form action="{{route('settings.settings')}}" method="POST">
            @csrf
            <div class="col-3 form-group">
                <label for="name">Nombre:</label>
                <input type="text" class="form-control" name="state-name">
            </div>
            <button type="submit" class="btn btn-sm btn-primary">Guardar</button>
        </form>
        @if($states->count() > 0)
            <p class="mt-3">Estados: </p>
            <ul>
                @foreach ($states as $state)
                    @if ($state->name == "Nuevo" | $state->name == "En Progreso" | $state->name == "Entregado" )
                        <li>{{$state->name}} (no editable)</li>
                    @else
                        <li>{{$state->name}}  |  <a href="{{route('settings.states.destroy', $state->id)}}">Eliminar</a></li>
                    @endif
                @endforeach
            </ul>
        @else
            <div class="alert alert-danger col-3 mt-3" role="alert">
                Todavía no tenes estados.
            </div>
        @endif
    </div>
    <div class="tab-pane fade" id="adduser" role="tabpanel" aria-labelledby="adduser-tab">
        <p class="mt-3">Invitar Usuario a Empresa:</p>
        <form action="{{route('settings.settings')}}" method="POST">
            @csrf
            <label for="invite-email">Email</label>
            <input class="form-control col-4 mb-3" type="email" name="invite-email">
            <button class="btn btn-sm btn-primary" type="submit">Invitar</button>
        </form>
    </div>
    <div class="tab-pane fade" id="perfil" role="tabpanel" aria-labelledby="perfil-tab">
        <p class="mt-3">Editar Perfil:</p>
        <form class="col-4" action="{{route('settings.settings')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <div class="row rounded">
                    <img style="border-radius: 50%; border: 1px solid lightgrey;" width= "200px" height="200px" src="{{url('storage/' . Auth::user()->img)}}" alt=""> 
                </div>
                <label for="user-image"></label>
                <input name="user-image" class="form-control" type="file" style="width: 46%;">
            </div>
            <div class="form-group">
                <label for="user-name">Nombre</label>
                <input type="text" class="form-control" name="user-name" value="{{Auth::user()->name}}">
            </div>
            <div class="form-group">
                <label for="user-email">Email</label>
                <input type="text" class="form-control" name="user-email" value="{{Auth::user()->email}}">
            </div>
            <button type="submit" class="btn btn-sm btn-primary">Editar</button>
        </form>
    </div>
    <div class="tab-pane fade" id="company" role="tabpanel" aria-labelledby="company-tab">
        <p class="mt-3">Editar Empresa:</p>
        <form class="col-4" action="{{route('settings.settings')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <div class="row rounded">
                    <img style="border-radius: 50%; border: 1px solid lightgrey;" width= "200px" height="200px" src="{{url('storage/' . Auth::user()->company->img)}}" alt=""> 
                </div>
                <label for="company-image"></label>
                <input name="company-image" class="form-control" type="file" style="width: 46%;">
            </div>
            <div class="form-group">
                <label for="company-name">Nombre Empresa</label>
                <input type="text" class="form-control" name="company-name" value="{{Auth::user()->company->name}}">
            </div>
            <button type="submit" class="btn btn-sm btn-primary">Editar</button>
        </form>
    </div>
</div>
@endsection