routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function() {

    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    
    Route::prefix('/settings')->name('settings.')->group(function() {
        Route::get('/', 'SettingsController@index');
        // Route::post('/', 'StateController@store')->name('store');
        // Route::post('/', 'StateController@store')->name('store');
        Route::post('/', 'SettingsController@settings')->name('settings');
        Route::prefix('/settings')->name('states.')->group(function() {
            Route::get('/{id}/destroy', 'StateController@destroy')->name('destroy');
        });
        Route::prefix('/customize')->name('customize.')->group(function() {
            Route::get('/', 'CustomizeController@index');
            //Falta armar los destroy de clients, products, y sales, pero tiene que validar si estan en uso a donde mover esos datos. o avisar que se van a borrar
            Route::prefix('/clients')->name('clients.')->group(function() {
                Route::get('/', 'CustomClientController@index');
                Route::post('/', 'CustomClientController@store')->name('store');
                Route::get('/{id}/destroy', 'CustomClientController@destroy')->name('destroy');
            });
            Route::prefix('/products')->name('products.')->group(function() {
                Route::get('/', 'CustomProductController@index');
                Route::post('/', 'CustomProductController@store')->name('store');
                Route::get('/{id}/destroy', 'CustomProductController@destroy')->name('destroy');
            });
            Route::prefix('/sales')->name('sales.')->group(function() {
                Route::get('/', 'CustomSaleController@index');
                Route::post('/', 'CustomSaleController@store')->name('store');
                Route::get('/{id}/destroy', 'CustomSaleController@destroy')->name('destroy');
            });
        });
    });

    Route::prefix('/sales')->name('sales.')->group(function() {
        Route::get('/destroy', 'SaleController@destroy')->name('destroy');
        Route::get('/', 'SaleController@index');
        Route::get('/new', 'SaleController@create')->name('create');
        Route::get('/{id}', 'SaleController@show')->name('show');
        Route::get('/{id}/edit', 'SaleController@edit')->name('edit');
        Route::post('/{id}/edit', 'SaleController@update')->name('update');
        Route::post('/new', 'SaleController@store')->name('store');
        Route::get('/{id}/edit/destroy', 'ProductSaleController@destroy')->name('product_destroy');
    });

    Route::prefix('/products')->name('products.')->group(function() {
        Route::get('/', 'ProductController@index');
        Route::get('/destroy', 'ProductController@destroy')->name('destroy');
        Route::get('/new', 'ProductController@create')->name('create');
        Route::get('/{id}/edit', 'ProductController@edit')->name('edit');
        Route::get('/{id}', 'ProductController@show')->name('show');
        Route::post('/new', 'ProductController@store')->name('store');
        Route::post('/{id}', 'ProductController@update')->name('update');
        Route::get('/{id}/edit/destroy', 'ProductProviderController@destroy')->name('provider_destroy');
        Route::post('/{id}/edit/add-provider', 'ProductProviderController@store')->name('add-provider');
    });

    Route::prefix('/clients')->name('clients.')->group(function() {
        Route::get('/destroy', 'ClientController@destroy')->name('destroy');
        Route::get('/', 'ClientController@index');
        Route::get('/new', 'ClientController@create')->name('create');
        Route::get('/{id}', 'ClientController@show')->name('show');
        Route::post('/new', 'ClientController@store')->name('store');
        Route::post('/{id}', 'ClientController@update')->name('update');
    });

    Route::prefix('/orders')->name('orders.')->group(function() {
        Route::get('/', 'SaleController@orders')->name('show_orders');
        Route::post('/', 'SaleController@orderUpdate')->name('orderUpdate');
    });

    Route::prefix('/providers')->name('providers.')->group(function() {
        Route::get('/', 'ProviderController@index')->name('index');
        Route::get('/{id}', 'ProviderController@show')->name('show');
        Route::get('/{id}/edit', 'ProviderController@edit')->name('edit');
        Route::post('/', 'ProviderController@store')->name('store');
        Route::post('/{id}', 'ProviderController@update')->name('update');
        Route::get('/destroy/{id}', 'ProviderController@destroy')->name('destroy');
        
    });
});

Route::get('logout', 'Auth\LoginController@logout');

Route::get('/artisan', 'ArtisanController@artisan')->name('artisan');

Route::get('/accept/{token}', 'InviteController@accept')->name('accept');
Route::post('/accept/{token}', 'SettingsController@registerInvite')->name('registerInvite');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'company_id', 'name', 'phone', 'email', 'adress', 'info'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        
    ];

    public function sales(){
        return $this->hasMany('App\Sale');
    }

    public function customClient(){
        return $this->belongsToMany('App\CustomClient', 'company_id');
    }
    public function customClients(){
        $custom_clients = CustomClient_pivot::where('client_id', $this->id)->get();
        return $custom_clients;
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use Illuminate\Http\Request;
use Auth;
use App\CustomClient;
use App\CustomClient_pivot;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::where('company_id', Auth::user()->company_id)->orderBy('created_at', 'desc')->get();
        $custom_fields = CustomClient::where('company_id', Auth::user()->company_id)->get();
        return view('clients.index')
        ->with('clients', $clients)
        ->with('custom_fields', $custom_fields);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $custom_clients = CustomClient::where('company_id', Auth::user()->company_id)->get();
        return view('clients.create')
        ->with('custom_clients', $custom_clients);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages = [
                'name.required' => 'Este campo es obligatorio',
                'name.min' => 'El nombre debe tener al menos 3 caracteres',
                'name.max' => 'El nombre no puede tener mas de 255 caracteres',
                'phone.numeric' => 'Este campo solo puede contener numeros',
                'phone.unique' => 'Este telefono ya ha sido usado',
                'email.unique' => 'Este email ya ha sido usado',
                'address.required' => 'Este campo es obligatorio',
        ];
        
        $validation = $request->validate([
            'name' => 'required|string|min:3|max:255',
            'phone' => 'nullable|numeric|unique:clients',
            'email' => 'nullable|unique:clients',
            'address' => 'required|max:255',
        ], $messages);        

        $client = new Client;
        $client->name = isset($request->name)? $request->name : null;
        $client->phone = isset($request->phone)? $request->phone : null;
        $client->email = isset($request->email)? $request->email : null;
        $client->address = isset($request->address)? $request->address : null;
        $client->info = isset($request->info)? $request->info : null;
        $client->company_id = Auth::user()->company_id;
        $client->save();

        if($request->custom_clients){
            /* CREAMOS LOS PRODUCTS VALUES EN LA TABLA PIVOT */
            foreach ($request->custom_clients as $i => $custom_client) {
            $custom_client_pivot = new CustomClient_pivot;
            $custom_client_pivot->custom_client_id = $custom_client['id'];
            $custom_client_pivot->company_id = Auth::user()->company_id;
            $custom_client_pivot->value = $custom_client['value'];
            $custom_client_pivot->client_id = $client->id;
            $custom_client_pivot->save();
            }
        }
        $clients = Client::where('company_id', Auth::user()->id)->orderBy('created_at', 'desc')->get();
        $custom_fields = CustomClient::where('company_id', Auth::user()->company_id)->get();
        return view('clients.index')
        ->with('clients', $clients)
        ->with('custom_fields', $custom_fields);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $id = (int)$id;
        $client = Client::find($id);
        $custom_fields = CustomClient::where('company_id', Auth::user()->company_id)->get();

        // return view('clients.show')
        // ->with('client', $client)
        // ->with('custom_fields', $custom_fields);
        
        if (Auth::user()->company_id == $client->company_id) {
            return view('clients.show')
            ->with('client', $client)
            ->with('custom_fields', $custom_fields);
        }else {
            abort(403);
        }
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    $messages = [
            'name.required' => 'Este campo es obligatorio',
            'name.min' => 'El nombre debe tener al menos 3 caracteres',
            'name.max' => 'El nombre no puede tener mas de 255 caracteres',
            'phone.numeric' => 'Este campo solo puede contener numeros',
            'phone.unique' => 'Este telefono ya ha sido usado',
            'email.unique' => 'Este email ya ha sido usado',
            'address.required' => 'Este campo es obligatorio',
    ];
    
    $validation = $request->validate([
        'name' => 'required|string|min:3|max:255',
        'phone' => 'nullable|numeric',
        'email' => 'nullable',
        'address' => 'required|max:255',
    ], $messages); 

        $client = Client::where('id', $id)->first();
        $client->name = $request->name;
        $client->phone = $request->phone;
        $client->email = $request->email;
        $client->address = $request->address;
        $client->info = $request->info;
        $client->save();

        if($request->custom_fields){
            /* EDITAMOS EL PIVOT TABLE */
            foreach ($request->custom_fields as $custom_field) {
                $custom_client_pivot = CustomClient_pivot::where([
                    ['client_id', $custom_field['client_id']],
                    ['id', $custom_field['custom_client_id']],
                ])->get();
                $custom_client_pivot[0]->value = $custom_field['value'];
                $custom_client_pivot[0]->save();
            }
        }

        $clients = Client::where('company_id', Auth::user()->id)->orderBy('created_at', 'desc')->get();
        $custom_fields = CustomClient::where('company_id', Auth::user()->company_id)->get();
        return view('clients.index')
        ->with('clients', $clients)
        ->with('custom_fields', $custom_fields);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $client = Client::where('id', $request->id);
        $client->delete();
        return back();
    }
}

resources/views/clients/create.blade.php
@extends('layouts.app')

@section('content')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Nuevo Cliente</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Compartir</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Exportar</button>
        </div>
    </div>
</div>
<div class="row d-flex justify-content-center">
    <div class="col-4">
        <form action="{{route('clients.store')}}" method="POST">
            @csrf
            <div class="form-group">
                <label for="name">Nombre y Apellido:</label>
                <input name="name" type="text" class="form-control @error('name') is-invalid @enderror" value="{{ old('name')}}">
                
                @error('name')
                    <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="phone">Telefono:</label>
                <input name="phone" type="text" class="form-control @error('phone') is-invalid @enderror" value=" {{old('phone')}} ">

                @error('phone')
                    <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input name="email" type="email" class="form-control @error('email') is-invalid @enderror" value=" {{old('email')}} ">

                @error('email')
                    <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="address">Ciudad:</label>
                <input name="address" type="text" class="form-control @error('address') is-invalid @enderror" value=" {{old('address')}} ">

                @error('address')
                    <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>
            <div>
                <label for="info">Info Extra:</label>
                <textarea class="form-control mb-3" name="info" cols="8" rows="3"></textarea>
            </div>
            @foreach ($custom_clients as $i => $custom_client)
                <div class="form-group">
                    <label for="custom_clients[{{$i}}]">{{ucfirst($custom_client->value)}}:</label>
                    <input class="form-control" type="text" name="custom_clients[{{$i}}][value]">
                    <input type="hidden" name="custom_clients[{{$i}}][id]" value="{{$custom_client->id}}">
                </div>
            @endforeach
            <button class="btn btn-success" type="submit">CARGAR CLIENTE</button>
        </form>
    </div>
</div>
@endsection

resources/views/clients/index.blade.php
@extends('layouts.app')

@section('content')
        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Tables</h1>
          {{-- <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.</p> --}}

          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Listado de Clientes</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Teléfono</th>
            <th>Email</th>
            <th>Ciudad</th>
            <th>Descripción</th>
            @foreach ($custom_fields as $custom_field)
                <th>
                    {{$custom_field->value}}
                </th>   
            @endforeach
            <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
            @foreach ($clients as $client)
            <tr>
                <td>
                    <a href="{{route('clients.show', $client->id)}}">{{$client->id}}</a>
                </td>
                <td>
                    <a href="{{route('clients.show', $client->id)}}">{{$client->name}}</a>
                </td>
                <td>{{$client->phone}}</td>
                <td>{{$client->email}}</td>
                <td>{{$client->adress}}</td>
                <td>{{$client->info}}</td>
                @foreach ($client->customClients() as $custom_clients)
                    @if ($client->customClients())
                        <td>
                            {{$custom_clients->value}}
                        </td>   
                    @endif
                @endforeach
                @if($client->customClients()->count() != $custom_fields->count())
                    @foreach ($custom_fields as $nada)
                        <td></td>
                    @endforeach
                @endif
                <td>
                    <div class="row d-flex justify-content-center">
                        
                        <a href="{{route ('clients.show', $client->id)}}"><i class="fas fa-edit"></i></a>
                        <form action="{{route ('clients.destroy')}}" method="GET">
                            <input type="hidden" name="id" value="{{$client->id}}">
                            <button style="border:none; background-color:transparent;" type="submit">
                                <i style="color:#007bff;" class="fas fa-trash"></i>
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
            @endforeach
        </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
@endsection

resources/views/clients/show.blade.php
@extends('layouts.app')

@section('content')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Editar Cliente</h1>
</div>
<div class="row d-flex justify-content-center">
    <div class="col-4">
        <form action="{{route('clients.update', $client->id)}}" method="POST">
            @csrf
            <div class="form-group">
                <label for="name">Nombre y Apellido:</label>
                <input name="name" type="text" class="form-control @error('name') is-invalid @enderror " value="{{$client->name}}">

                @error('name')
                    <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="phone">Telefono:</label>
                <input name="phone" type="text" class="form-control @error('phone') is-invalid @enderror " value="{{$client->phone}}">

                @error('phone')
                    <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input name="email" type="email" class="form-control @error('email') is-invalid @enderror " value="{{$client->email}}">

                @error('email')
                    <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="address">Ciudad:</label>
                <input name="address" type="text" class="form-control @error('address') is-invalid @enderror " value="{{$client->address}}">

                @error('address')
                    <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>
            <div>
                <label for="info">Info Extra:</label>
                <textarea class="form-control mb-3" name="info" cols="8" rows="3">{{$client->info}}</textarea>
            </div>
            {{-- @dd($client->customClients()) --}}
            {{-- @dd($client->customClients()[0]->CustomClient()) --}}
            @if($client->customClients()->count() != 0)
                @foreach ($client->customClients() as $i => $custom_client_pivot)
                        <div class="form-group">
                            <label for="custom_fields[{{$i}}][value]">{{$client->customClients()[$i]->customClient()[0]->value}}</label>
                            <input class="form-control" type="text" name="custom_fields[{{$i}}][value]" value="{{$custom_client_pivot->value}}">
                            <input type="text" hidden name="custom_fields[{{$i}}][client_id]" value="{{$client->id}}">
                            <input type="text" hidden name="custom_fields[{{$i}}][custom_client_id]" value="{{$custom_client_pivot->id}}">
                        </div>
                @endforeach
            @else
                @foreach ($custom_fields as $i => $custom_field)
                    <label for="custom_fields[{{$i}}][value]">{{$custom_field->value}}</label>
                    <input class="form-control mb-3" type="text" name="custom_fields[{{$i}}][value]">
                    <input type="text" hidden name="custom_fields[{{$i}}][client_id]" value="{{$client->id}}">
                    <input type="text" hidden name="custom_fields[{{$i}}][custom_client_id]" value="{{$custom_field->id}}">
                @endforeach
            @endif
            <button class="btn btn-success" type="submit">EDITAR CLIENTE</button>
        </form>
    </div>
</div>
<div class="row">
    <h4>Ventas:</h4>
    {{-- @dd($client->sales) --}}
    @if ($client->sales->count() != 0)
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Fecha</th>
                    <th scope="col">Estado</th>
                    <th scope="col">Costo</th>
                    <th scope="col">Ganancia</th>
                    <th scope="col">Info</th>
                    <th scope="col">Fecha de Entrega</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($client->sales as $client_sale)
                    <tr>
                        <th>{{date('d-m-Y', strtotime($client_sale->created_at))}}</th>
                        <td>{{$client_sale->bringStates['name']}}</td>
                        <td>{{$client_sale->cost}}</td>
                        <td>{{$client_sale->revenue}}</td>
                        <td>{{$client_sale->info}}</td>
                        <td>{{$client_sale->date}}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
</div>
    <p>Este cliente no tiene ventas.</p>
@endif
@endsection