routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function() {

    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    
    Route::prefix('/settings')->name('settings.')->group(function() {
        Route::get('/', 'SettingsController@index');
        // Route::post('/', 'StateController@store')->name('store');
        // Route::post('/', 'StateController@store')->name('store');
        Route::post('/', 'SettingsController@settings')->name('settings');
        Route::prefix('/settings')->name('states.')->group(function() {
            Route::get('/{id}/destroy', 'StateController@destroy')->name('destroy');
        });
        Route::prefix('/customize')->name('customize.')->group(function() {
            Route::get('/', 'CustomizeController@index');
            //Falta armar los destroy de clients, products, y sales, pero tiene que validar si estan en uso a donde mover esos datos. o avisar que se van a borrar
            Route::prefix('/clients')->name('clients.')->group(function() {
                Route::get('/', 'CustomClientController@index');
                Route::post('/', 'CustomClientController@store')->name('store');
                Route::get('/{id}/destroy', 'CustomClientController@destroy')->name('destroy');
            });
            Route::prefix('/products')->name('products.')->group(function() {
                Route::get('/', 'CustomProductController@index');
                Route::post('/', 'CustomProductController@store')->name('store');
                Route::get('/{id}/destroy', 'CustomProductController@destroy')->name('destroy');
            });
            Route::prefix('/sales')->name('sales.')->group(function() {
                Route::get('/', 'CustomSaleController@index');
                Route::post('/', 'CustomSaleController@store')->name('store');
                Route::get('/{id}/destroy', 'CustomSaleController@destroy')->name('destroy');
            });
        });
    });

    Route::prefix('/sales')->name('sales.')->group(function() {
        Route::get('/destroy', 'SaleController@destroy')->name('destroy');
        Route::get('/', 'SaleController@index');
        Route::get('/new', 'SaleController@create')->name('create');
        Route::get('/{id}', 'SaleController@show')->name('show');
        Route::get('/{id}/edit', 'SaleController@edit')->name('edit');
        Route::post('/{id}/edit', 'SaleController@update')->name('update');
        Route::post('/new', 'SaleController@store')->name('store');
        Route::get('/{id}/edit/destroy', 'ProductSaleController@destroy')->name('product_destroy');
    });

    Route::prefix('/products')->name('products.')->group(function() {
        Route::get('/', 'ProductController@index');
        Route::get('/destroy', 'ProductController@destroy')->name('destroy');
        Route::get('/new', 'ProductController@create')->name('create');
        Route::get('/{id}/edit', 'ProductController@edit')->name('edit');
        Route::get('/{id}', 'ProductController@show')->name('show');
        Route::post('/new', 'ProductController@store')->name('store');
        Route::post('/{id}', 'ProductController@update')->name('update');
        Route::get('/{id}/edit/destroy', 'ProductProviderController@destroy')->name('provider_destroy');
        Route::post('/{id}/edit/add-provider', 'ProductProviderController@store')->name('add-provider');
    });

    Route::prefix('/clients')->name('clients.')->group(function() {
        Route::get('/destroy', 'ClientController@destroy')->name('destroy');
        Route::get('/', 'ClientController@index');
        Route::get('/new', 'ClientController@create')->name('create');
        Route::get('/{id}', 'ClientController@show')->name('show');
        Route::post('/new', 'ClientController@store')->name('store');
        Route::post('/{id}', 'ClientController@update')->name('update');
    });

    Route::prefix('/orders')->name('orders.')->group(function() {
        Route::get('/', 'SaleController@orders')->name('show_orders');
        Route::post('/', 'SaleController@orderUpdate')->name('orderUpdate');
    });

    Route::prefix('/providers')->name('providers.')->group(function() {
        Route::get('/', 'ProviderController@index')->name('index');
        Route::get('/{id}', 'ProviderController@show')->name('show');
        Route::get('/{id}/edit', 'ProviderController@edit')->name('edit');
        Route::post('/', 'ProviderController@store')->name('store');
        Route::post('/{id}', 'ProviderController@update')->name('update');
        Route::get('/destroy/{id}', 'ProviderController@destroy')->name('destroy');
        
    });
});

Route::get('logout', 'Auth\LoginController@logout');

Route::get('/artisan', 'ArtisanController@artisan')->name('artisan');

Route::get('/accept/{token}', 'InviteController@accept')->name('accept');
Route::post('/accept/{token}', 'SettingsController@registerInvite')->name('registerInvite');

app/Provider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Provider extends Model
{
    //
}

app/Http/Controllers/ProviderController.php
<?php

namespace App\Http\Controllers;

use App\Provider;
use Illuminate\Http\Request;
use Auth;

class ProviderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $providers = Provider::where('company_id', Auth::user()->id)->get();
        return view('providers.index')->with('providers', $providers);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $provider = new Provider;
        $provider->name = $request->name;
        $provider->company_id = Auth::user()->company_id;
        $provider->phone = $request->phone;
        $provider->address = $request->address;
        $provider->city = $request->city;
        $provider->info = $request->info;
        $provider->save();
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Provider  $provider
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $provider = Provider::find($id);
        return view('providers.show')->with('provider', $provider);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Provider  $provider
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $provider = Provider::find($id);
        return view('providers.edit')->with('provider', $provider);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Provider  $provider
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $messages = [
            'name.required' => 'Este campo es obligatorio',
            'name.min' => 'El nombre debe tener al menos 3 caracteres',
            'name.max' => 'El nombre no puede tener mas de 255 caracteres',
            'phone.numeric' => 'Este campo solo puede contener numeros',
            'phone.unique' => 'Este telefono ya ha sido usado',
            'email.unique' => 'Este email ya ha sido usado',
            'address.required' => 'Este campo es obligatorio',
        ];
    
        $validation = $request->validate([
            'name' => 'required|string|min:3|max:255',
            'phone' => 'nullable',
            'address' => 'required|max:255',
        ], $messages); 

        $provider = Provider::find($id);
        $provider->name = $request->name;
        $provider->company_id = Auth::user()->company_id;
        $provider->phone = $request->phone;
        $provider->address = $request->address;
        $provider->city = $request->city;
        $provider->info = $request->info;
        $provider->save();
        return redirect('/providers');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Provider  $provider
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $provider = Provider::find($id);
        $provider->delete();
        return back();
    }
}

resources/views/providers/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Editar Proveedor</h1>
</div>
<div class="row d-flex justify-content-center">
    <div class="col-4">
        <form action="{{route('providers.update', $provider->id)}}" method="POST">
            @csrf
            <div class="form-group">
                <label for="name">Nombre:</label>
                <input name="name" type="text" class="form-control @error('name') is-invalid @enderror " value="{{$provider->name}}">

                @error('name')
                    <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="phone">Telefono:</label>
                <input name="phone" type="text" class="form-control @error('phone') is-invalid @enderror " value="{{$provider->phone}}">

                @error('phone')
                    <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="address">Dirección:</label>
                <input name="address" type="text" class="form-control @error('address') is-invalid @enderror " value="{{$provider->address}}">

                @error('address')
                    <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="city">Ciudad:</label>
                <input name="city" type="text" class="form-control @error('city') is-invalid @enderror " value="{{$provider->city}}">

                @error('city')
                    <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>
            <div>
                <label for="info">Detalles:</label>
                <textarea class="form-control mb-3" name="info" cols="8" rows="3">{{$provider->info}}</textarea>
            </div>
            <button class="btn btn-success" type="submit">EDITAR CLIENTE</button>
        </form>
    </div>
</div>
@endsection

resources/views/providers/index.blade.php
@extends('layouts.app')

@section('content')
        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          {{-- <h1 class="h3 mb-2 text-gray-800">Tables</h1> --}}
          <button class="btn btn-primary mb-4" data-toggle="modal" data-target="#newProvider">Cargar Proveedor</button>
          {{-- <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.</p> --}}

          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Listado de Proveedores</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Teléfono</th>
            <th>Dirección</th>
            <th>Ciudad</th>
            <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
            @foreach ($providers as $provider)
            <tr>
                <td>
                    <a href="{{route('providers.show', $provider->id)}}">{{$provider->id}}</a>
                </td>
                <td>
                    <a href="{{route('providers.show', $provider->id)}}">{{$provider->name}}</a>
                </td>
                <td>{{$provider->phone}}</td>
                <td>{{$provider->address}}</td>
                <td>{{$provider->city}}</td>
                <td>
                    <div class="row d-flex justify-content-center">
                        <a class="m-2" href="{{route('providers.show', $provider->id)}}">
                            <i class="far fa-eye"></i>
                        </a>
                        <a class="m-2" href="{{route ('providers.edit', $provider->id)}}">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="m-2" href="#">
                            <i onclick="destroyProvider({{$provider->id}})" style="color:#007bff;" class="fas fa-trash"></i>
                        </a>
                    </div>
                </td>
            </tr>
            @endforeach
        </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

<!-- Modal -->
<div class="modal fade" id="newProvider" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="{{route('providers.store')}}" method="POST">
                @csrf
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Cargar Proveedor</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <label for="name">Nombre</label>
                    <input type="text" name="name" id="" class="form-control">
                    <label for="phone">Teléfono</label>
                    <input type="text" name="phone" id="" class="form-control">
                    <label for="address">Dirección</label>
                    <input type="text" name="address" id="" class="form-control">
                    <label for="city">Ciudad</label>
                    <input type="text" name="city" id="" class="form-control">
                    <label for="info">Detalles:</label>
                    <input type="text" name="info" id="" class="form-control">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </form>
        </div>
    </div>
    </div>

    <script>
        function destroyProvider(provider_id)
        {
            fetch('/providers/destroy/' + provider_id, {
			method: 'get',
            }).then(function(response){
                return response.text();
            })
            location.reload();
        }
    </script>

@endsection

resources/views/providers/show.blade.php
@extends('layouts.app')

@section('content')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">{{$provider->name}}</h1>
</div>
<div class="row d-flex justify-content-center">
    <div class="col-4">
        
    </div>
</div>
@endsection