routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function() {

    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    
    Route::prefix('/settings')->name('settings.')->group(function() {
        Route::get('/', 'SettingsController@index');
        // Route::post('/', 'StateController@store')->name('store');
        // Route::post('/', 'StateController@store')->name('store');
        Route::post('/', 'SettingsController@settings')->name('settings');
        Route::prefix('/settings')->name('states.')->group(function() {
            Route::get('/{id}/destroy', 'StateController@destroy')->name('destroy');
        });
        Route::prefix('/customize')->name('customize.')->group(function() {
            Route::get('/', 'CustomizeController@index');
            //Falta armar los destroy de clients, products, y sales, pero tiene que validar si estan en uso a donde mover esos datos. o avisar que se van a borrar
            Route::prefix('/clients')->name('clients.')->group(function() {
                Route::get('/', 'CustomClientController@index');
                Route::post('/', 'CustomClientController@store')->name('store');
                Route::get('/{id}/destroy', 'CustomClientController@destroy')->name('destroy');
            });
            Route::prefix('/products')->name('products.')->group(function() {
                Route::get('/', 'CustomProductController@index');
                Route::post('/', 'CustomProductController@store')->name('store');
                Route::get('/{id}/destroy', 'CustomProductController@destroy')->name('destroy');
            });
            Route::prefix('/sales')->name('sales.')->group(function() {
                Route::get('/', 'CustomSaleController@index');
                Route::post('/', 'CustomSaleController@store')->name('store');
                Route::get('/{id}/destroy', 'CustomSaleController@destroy')->name('destroy');
            });
        });
    });

    Route::prefix('/sales')->name('sales.')->group(function() {
        Route::get('/destroy', 'SaleController@destroy')->name('destroy');
        Route::get('/', 'SaleController@index');
        Route::get('/new', 'SaleController@create')->name('create');
        Route::get('/{id}', 'SaleController@show')->name('show');
        Route::get('/{id}/edit', 'SaleController@edit')->name('edit');
        Route::post('/{id}/edit', 'SaleController@update')->name('update');
        Route::post('/new', 'SaleController@store')->name('store');
        Route::get('/{id}/edit/destroy', 'ProductSaleController@destroy')->name('product_destroy');
    });

    Route::prefix('/products')->name('products.')->group(function() {
        Route::get('/', 'ProductController@index');
        Route::get('/destroy', 'ProductController@destroy')->name('destroy');
        Route::get('/new', 'ProductController@create')->name('create');
        Route::get('/{id}/edit', 'ProductController@edit')->name('edit');
        Route::get('/{id}', 'ProductController@show')->name('show');
        Route::post('/new', 'ProductController@store')->name('store');
        Route::post('/{id}', 'ProductController@update')->name('update');
        Route::get('/{id}/edit/destroy', 'ProductProviderController@destroy')->name('provider_destroy');
        Route::post('/{id}/edit/add-provider', 'ProductProviderController@store')->name('add-provider');
    });

    Route::prefix('/clients')->name('clients.')->group(function() {
        Route::get('/destroy', 'ClientController@destroy')->name('destroy');
        Route::get('/', 'ClientController@index');
        Route::get('/new', 'ClientController@create')->name('create');
        Route::get('/{id}', 'ClientController@show')->name('show');
        Route::post('/new', 'ClientController@store')->name('store');
        Route::post('/{id}', 'ClientController@update')->name('update');
    });

    Route::prefix('/orders')->name('orders.')->group(function() {
        Route::get('/', 'SaleController@orders')->name('show_orders');
        Route::post('/', 'SaleController@orderUpdate')->name('orderUpdate');
    });

    Route::prefix('/providers')->name('providers.')->group(function() {
        Route::get('/', 'ProviderController@index')->name('index');
        Route::get('/{id}', 'ProviderController@show')->name('show');
        Route::get('/{id}/edit', 'ProviderController@edit')->name('edit');
        Route::post('/', 'ProviderController@store')->name('store');
        Route::post('/{id}', 'ProviderController@update')->name('update');
        Route::get('/destroy/{id}', 'ProviderController@destroy')->name('destroy');
        
    });
});

Route::get('logout', 'Auth\LoginController@logout');

Route::get('/artisan', 'ArtisanController@artisan')->name('artisan');

Route::get('/accept/{token}', 'InviteController@accept')->name('accept');
Route::post('/accept/{token}', 'SettingsController@registerInvite')->name('registerInvite');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;
use App\CustomProduct_pivot;
use Auth;
use App\ProductProvider;

class Product extends Model
{
        /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'company_id', 'measure', 'price', 'cost', 'name', 'time'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        
    ];

    public function sale(){
        return $this->belongsTo('App\Sale');
    }

    public function sales(){
        return $this->belongsToMany(Sale::class, 'product_sales');
    }

    public function customProducts(){
        $custom_products = CustomProduct_pivot::where('product_id', $this->id)->get();
        return $custom_products;
    }

    public function providers(){
        // $providers = ProductProvider::where('product_id', $this->id)->get();
        $providers = DB::table('providers')
            ->join('product_providers', 'providers.id', '=', 'product_providers.provider_id')
            ->where('product_providers.product_id', $this->id)
            ->select('providers.name', 'providers.phone', 'providers.address', 'providers.city', 'product_providers.cost', 'product_providers.info', 'product_providers.id')->get();
        // dd($providers);
        return $providers;
    }

    public function hasProviders(){
        $providers = ProductProvider::where('product_id', $this->id)->get();
        return $providers;
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use Auth;
use App\CustomProduct;
use App\CustomProduct_pivot;
use App\Provider;
use App\ProductProvider;
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::where('company_id', Auth::user()->company_id)->orderBy('created_at', 'desc')->get();
        $custom_fields = CustomProduct::where('company_id', Auth::user()->company_id)->get();
        return view('products.index')
        ->with('products', $products)
        ->with('custom_fields', $custom_fields);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $providers = Provider::where('company_id', Auth::user()->company_id)->get();
        $custom_products = CustomProduct::where('company_id', Auth::user()->company_id)->get();
        return view('products.create')
        ->with('custom_products', $custom_products)
        ->with('providers', $providers);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages = [
            'name.required' => 'Este campo es obligatorio',
            'price.required' => 'Este campo es obligatorio',
            'price.numeric' => 'Este campo solo puede contener numeros',
            // 'cost.required' => 'Este campo es obligatorio',
            // 'cost.numeric' => 'Este campo solo puede contener numeros',
        ];

        $validation = $request->validate([
            'name' => 'required',
            'price' => 'required|numeric',
            // 'cost' => 'required|numeric',
        ], $messages);
        
        // dd($request);

        
        $product = new Product;
        $product->name = isset($request->name)? $request->name : null;
        $product->measure = isset($request->measure)? $request->measure : null;
        $product->price = isset($request->price)? $request->price : null;
        // $product->cost = isset($request->cost)? $request->cost : null;
        $product->time = isset($request->time)? $request->time : null;
        $product->company_id = Auth::user()->company_id;
        $product->save();

        /* CREAMOS LOS PRODUCTS VALUES EN LA TABLA PIVOT */
        if($request->custom_products){
            
            foreach ($request->custom_products as $i => $custom_product) {
                $custom_product_pivot = new CustomProduct_pivot;
                $custom_product_pivot->product_id = $product->id;
                $custom_product_pivot->company_id = Auth::user()->company_id;
                $custom_product_pivot->custom_product_id = $custom_product['id'];
                $custom_product_pivot->value = $custom_product['value'];
                $custom_product_pivot->save();
            }
            /*  */
        }

        /* CREAMOS LOS PROVEEDORES DEL PRODUCTO EN TABLA PIVOT */
        if ($request->providers) {
            foreach ($request->providers as $provider) {
                $product_provider = new ProductProvider;
                $product_provider->cost = $provider['cost'];
                $product_provider->product_id = $product->id;
                $product_provider->company_id = Auth::user()->company_id;
                $product_provider->provider_id = $provider['provider_id'];
                $product_provider->save();
            }
        }

        return redirect('products');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $products
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $id = (int)$id;
        $product = Product::find($id);
        $custom_fields = CustomProduct::where('company_id', Auth::user()->company_id)->get();

        if (Auth::user()->company_id == $product->company_id) {
            return view('products.show')
            ->with('product', $product)
            ->with('custom_fields', $custom_fields);
        }else {
            abort(403);
        }

        return view('products.show')
        ->with('product', $product)
        ->with('custom_fields', $custom_fields);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $products
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $id = (int)$id;
        $product = Product::find($id);
        $custom_fields = CustomProduct::where('company_id', Auth::user()->company_id)->get();
        $product_provider = ProductProvider::where('product_id', $id)->get();
        $providers = Provider::where('company_id', Auth::user()->company_id)->get();
        // dd($product_provider);

        if (Auth::user()->company_id == $product->company_id) {
            return view('products.edit')
            ->with('product', $product)
            ->with('custom_fields', $custom_fields)
            ->with('product_provider', $product_provider)
            ->with('providers', $providers);
        }else {
            abort(403);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $products
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $messages = [
            'name.required' => 'Este campo es obligatorio',
            'price.required' => 'Este campo es obligatorio',
            'price.numeric' => 'Este campo solo puede contener numeros',
            'cost.required' => 'Este campo es obligatorio',
            'cost.numeric' => 'Este campo solo puede contener numeros',
        ];

        $validation = $request->validate([
            'name' => 'required',
            'price' => 'required|numeric',
            'cost' => 'required|numeric',
        ], $messages);

        
        /* GUARDAMOS EL PRODUCTO */
        $product = Product::find($id);
        $product->name = $request->name;
        $product->price = $request->price;
        $product->cost = $request->cost;
        $product->measure = $request->measure;
        $product->time = $request->time;
        $product->save();

        /* EDITAMOS EL PIVOT TABLE */
        if ($request->custom_fields) {
            foreach ($request->custom_fields as $custom_field) {
                $custom_product_pivot = CustomProduct_pivot::where([
                    ['product_id', $custom_field['product_id']],
                    ['id', $custom_field['custom_product_id']],
                ])->get();
                $custom_product_pivot[0]->value = $custom_field['value'];
                $custom_product_pivot[0]->save();
            }
        }

        return redirect('products');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $products
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        /* ELIMINAMOS EL PRODUCTO */
        $products = Product::where('id', $request->id);
        $products->delete();

        /* ELIMINAMOS LA TABLA PIVOT DEL PRODUCTO */
        $custom_product_pivot = CustomProduct_pivot::where('product_id', $request->id)->get();
        foreach ($custom_product_pivot as $custom_fields) {
            $custom_fields->delete();
        }
        return back();
    }
}

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Editar Producto</h1>
</div>
    <div class="row d-flex justify-content-center">
        <div class="col-md-8">
            <form action="{{route('products.update', $product->id)}}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="name">Nombre Producto:</label>
                    <input name="name" type="text" class="form-control @error('name') is-invalid @enderror" required value="{{$product->name}}">

                    @error('name')
                        <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="price">Precio:</label>
                    <input name="price" type="number" class="form-control @error('price') is-invalid @enderror" required value="{{$product->price}}">

                    @error('price')
                        <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>
                {{-- <div class="form-group">
                    <label for="cost">Costo:</label>
                    <input name="cost" type="number" class="form-control @error('cost') is-invalid @enderror" value="{{$product->cost}}">

                    @error('cost')
                        <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div> --}}
                <div class="form-group">
                    <label for="measure">Medidas:</label>
                    <input name="measure" type="text" class="form-control" value="{{$product->measure}}">
                </div>
                {{-- <div class="form-group">
                    <label for="time">Tiempo de Producción (en semanas):</label>
                    <input name="time" type="number" class="form-control" value="{{$product->time}}">
                </div> --}}
                {{-- @dd($product->customProducts()) --}}
                @if($product->customProducts()->count() != 0)
                    @foreach ($product->customProducts() as $i => $custom_product_pivot)
                            <div class="form-group">
                                <label for="custom_fields[{{$i}}][value]">{{$product->customProducts()[$i]->customProduct()[0]->value}}</label>
                                <input class="form-control" type="text" name="custom_fields[{{$i}}][value]" value="{{$custom_product_pivot->value}}">
                                <input type="text" hidden name="custom_fields[{{$i}}][product_id]" value="{{$product->id}}">
                                <input type="text" hidden name="custom_fields[{{$i}}][custom_product_id]" value="{{$custom_product_pivot->id}}">
                            </div>
                    @endforeach
                @else
                    @foreach ($custom_fields as $i => $custom_field)
                        <label for="custom_fields[{{$i}}][value]">{{$custom_field->value}}</label>
                        <input class="form-control mb-3" type="text" name="custom_fields[{{$i}}][value]">
                        <input type="text" hidden name="custom_fields[{{$i}}][product_id]" value="{{$product->id}}">
                        <input type="text" hidden name="custom_fields[{{$i}}][custom_product_id]" value="{{$custom_field->id}}">
                    @endforeach
                @endif
            </form>
            <a class="btn btn-secondary" href="./">Cancelar</a>
            <button class="btn btn-success" type="submit">Guardar</button>
        </div>
    </div>

    <div class="row d-flex justify-content-center">
        <div class="col-md-12">
            <hr style="background-color:red;">
            <div class="row">
                <h3>Proveedores:</h3>
                <a class="btn btn-primary" style="margin-left:20px;" href="#" data-toggle="modal" data-target="#addProviderModal">
                    Agregar Proveedor
                </a>
            </div>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Costo</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Teléfono</th>
                    <th scope="col">Ciudad</th>
                    <th scope="col">Acciones</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($product->providers() as $product_provider)
                    {{-- @dd($product_provider) --}}
                        <tr>
                            <td scope="row">{{$product_provider->id}}</td>
                            <td>${{number_format($product_provider->cost)}}</td>
                            <td>{{$product_provider->name}}</td>
                            <td>{{$product_provider->phone}}</td>
                            <td>{{$product_provider->city}}</td>
                            <td>
                                {{-- @dd($product->hasProviders()) --}}
                                @if(count($product->hasProviders()) > 1)
                                    <form action="{{route('products.provider_destroy', $product_provider->id)}}" method="GET">
                                        <input type="hidden" name="id" value="{{$product_provider->id}}">
                                        <button style="border:none; background-color:transparent;" type="submit">
                                            <i style="color:#007bff;" class="fas fa-trash"></i>
                                        </button>
                                    </form>
                                @else
                                (si o si tiene que tener un proveedor)
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

        </div>
    </div>


    <div class="modal fade" id="addProviderModal" tabindex="-1" role="dialog" aria-labelledby="addProviderModalLabel" aria-hidden="true">
        <form action="" name="addProviderProduct" id="addProviderProduct" method="post">
            @csrf
            <input type="text" hidden value="{{$product->id}}" name="productId" id="productId">
            <div class="modal-dialog" role="document">
                <div class="modal-content" style="padding: 15px;">
                    <div class="modal-header">
                    <h5 class="modal-title" id="addProviderModalLabel">Agregar Proveedor a {{$product->name}}:</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                        <div class="row d-flex justify-content-between">
                            <select class="form-control col-md-8" name="provider_id" id="">
                                <option value="null" selected disabled>Proveedor</option>
                                @foreach ($providers as $provider)
                                    <option value="{{$provider->id}}">{{$provider->name}}</option>
                                @endforeach
                            </select>
                            <input type="integer" name="provider_cost" class="form-control col-md-3" placeholder="Costo">
                        </div>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Agregar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>


    <script>
        const addProviderProduct = document.getElementById('addProviderProduct');
        const productId = document.getElementById('productId').value;
        addProviderProduct.addEventListener('submit', function(e) {
            e.preventDefault();
            const formData = new FormData(this);
            fetch('/products/' + productId + '/edit/add-provider', {
                method: 'post',
                body: formData
            }).then(function(response){
                return response.text();
            })
            location.reload();
        })
    </script>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">{{$product->name}}</h1> - <h1>{{$product->measure}}</h1> - <h1>${{$product->price}}</h1>
</div>
<div class="row d-flex justify-content-center">

    <h3>Proveedores:</h3>
</div>
<div class="row">
    @if (count($product->providers()) != 0)
    <hr>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Costo</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Teléfono</th>
                    <th scope="col">Ciudad</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($product->providers() as $product_provider)
                    {{-- @dd($product_provider->provider()->name) --}}
                    <tr>
                        <th scope="row">{{$product_provider->provider()->id}}</th>
                        <td>${{number_format($product_provider->cost)}}</td>
                        <td>{{$product_provider->provider()->name}}</td>
                        <td>{{$product_provider->provider()->phone}}</td>
                        <td>{{$product_provider->provider()->city}}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p>Este producto no tiene proveedores</p>
    @endif
</div>
@endsection